### ISSUE TITLE
Add Basic Framework

### ISSUE THREAD

**Issue by 9000-volts** [geckogames/splat2#1]
We need to make the basic stuff for the project.

**Comment by 1dharmadav** [comment]
????

**Comment by GD-Plasman** [comment]
We're working on a recode for SPLAT.

**Comment by 9000-volts** [comment]
I'm working on getting the basic framework laid out. That's what this issue is for: to discuss that.
I started by making the splat canvas take up the whole page this time, with a gradient background.
BTW we are using coffeescript this time; it is a neat syntax that turns into js.

**Comment by 9000-volts** [comment]
To see what I have done so far (pushed to the branch), see https://cdn.rawgit.com/geckogames/splat2/add-basic-framework-%231/index.html.

**Comment by 9000-volts** [comment]
Currently working on buttons for main screen.
For the record, they are 200x50, background #2b2b2b, Font 'Sans' 20 (GIMP), Center-Aligned
