### ISSUE TITLE
Graphics Colors: Grass

### ISSUE THREAD

**Issue by 9000-volts** [geckogames/splat2#13]
I was thinking to use http://www.colourlovers.com/palette/264688/Grass_Green

**Comment by AnolisSagrei** [comment]
I was thinking of something a bit brighter but this is good.

On Oct 25, 2015, at 11:02 AM, htmlguy <notifications@github.com<mailto:notifications@github.com>> wrote:

I was thinking to use http://www.colourlovers.com/palette/264688/Grass_Green
