### ISSUE TITLE
Add additional README.md documentation.

### ISSUE THREAD

**Issue by 9000-volts** [geckogames/splat2#2]
I made the file README.md very quickly and didn't have very much proper information about the project, it's precursor, why we redid the game, what's going to be different etc.
Can somebody else volunteer to write this? I am currently working on issue #1.
**Note:** This change does _not_ have to be done in a separate branch, as it is very minor.

**Comment by GD-Plasman** [comment]
I'm good at writing stuff.

**Comment by 9000-volts** [comment]
Thanks! You can post additional Qs here for us to discuss what should go into this.
Please note we are using waffle.io again: https://waffle.io/geckogames/splat2

**Comment by htmlguy** [comment]
Please note we are using waffle.io again: https://waffle.io/geckogames/

**Comment by 9000-volts** [comment]
When you are writing, use GFM, the format used for the README. See https://help.github.com/articles/writing-on-github/ to learn how.
Also, do this work in the `develop` branch, not the main one.

**Comment by GD-Plasman** [comment]
I think I'm done, any things I should add on to it?

**Comment by 9000-volts** [comment]
Looks good, but I think it needs a bit more about what is going to be done differently from the original SPLAT.

**Comment by GD-Plasman** [comment]
What things are different, exactly? I know more levels, enhanced (and more consistent) graphics,  what else?

**Comment by 9000-volts** [comment]
- Better Code
- More Consistent Graphics
- Animated Sprites
- More Levels
- Fix Bad Bugs
- Consistent FPS Rate
- Full-page canvas
- Easier to Contribute due to Reductionism & OOP
- Etc.
